# Generated by Django 5.2 on 2025-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
