# Generated by Django 5.2 on 2025-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterapp', '0002_director_alter_moviesinfo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesinfo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
