# Generated by Django 5.2 on 2025-04-12 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asterapp', '0007_censorinfo_moviesinfo_censor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesinfo',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='asterapp.director'),
        ),
    ]
